steps:
  ## Ads Packages
  - label: ":snowflake: Run Tests - Snowflake: Ads Packages :money_with_wings:"
    key: "run_dbt_snowflake_ads"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_SNOWFLAKE_DBT_ACCOUNT"
            - "CI_SNOWFLAKE_DATABASE_FT_UTILS"
            - "CI_SNOWFLAKE_DBT_PASS"
            - "CI_SNOWFLAKE_DBT_ROLE_FT_UTILS_TEST"
            - "CI_SNOWFLAKE_DBT_USER"
            - "CI_SNOWFLAKE_DBT_WAREHOUSE"
    commands: |
      bash .buildkite/scripts/ads_run_models.sh snowflake twitter_ads


  # - label: ":postgres: Run Tests - Postgres: Ads Packages :money_with_wings:"
  #   key: "run-dbt-postgres-ads"
  #   plugins:
  #     - docker#v3.13.0:
  #         image: "python:3.8"
  #         shell: [ "/bin/bash", "-e", "-c" ]
  #         environment:
  #           - "BASH_ENV=/tmp/.bashrc"
  #           - "CI_POSTGRES_DBT_DBNAME"
  #           - "CI_POSTGRES_DBT_HOST"
  #           - "CI_POSTGRES_DBT_PASS"
  #           - "CI_POSTGRES_DBT_USER"
  #   commands: |
  #     bash .buildkite/scripts/ads_run_models.sh postgres 

  # - label: ":gcloud: Run Tests - BigQuery: Ads Packages :money_with_wings:"
  #   key: "run_dbt_bigquery_ads"
  #   plugins:
  #     - docker#v3.13.0:
  #         image: "python:3.8"
  #         shell: [ "/bin/bash", "-e", "-c" ]
  #         environment:
  #           - "BASH_ENV=/tmp/.bashrc"
  #           - "GCLOUD_SERVICE_KEY"
  #   commands: |
  #     bash .buildkite/scripts/ads_run_models.sh bigquery

  # - label: ":amazon-redshift: Run Tests - Redshift: Ads Packages :money_with_wings:"
  #   key: "run_dbt_redshift_ads"
  #   plugins:
  #     - docker#v3.13.0:
  #         image: "python:3.8"
  #         shell: [ "/bin/bash", "-e", "-c" ]
  #         environment:
  #           - "BASH_ENV=/tmp/.bashrc"
  #           - "CI_REDSHIFT_DBT_DBNAME"
  #           - "CI_REDSHIFT_DBT_HOST"
  #           - "CI_REDSHIFT_DBT_PASS"
  #           - "CI_REDSHIFT_DBT_USER"
  #   commands: |
  #     bash .buildkite/scripts/ads_run_models.sh redshift

  # - label: ":bricks: Run Tests - Databricks: Ads Packages :money_with_wings:"
  #   key: "run_dbt_databricks_ads"
  #   plugins:
  #     - docker#v3.13.0:
  #         image: "python:3.8"
  #         shell: [ "/bin/bash", "-e", "-c" ]
  #         environment:
  #           - "BASH_ENV=/tmp/.bashrc"
  #           - "CI_DATABRICKS_DBT_HOST"
  #           - "CI_DATABRICKS_DBT_HTTP_PATH"
  #           - "CI_DATABRICKS_DBT_TOKEN"
  #   commands: |
  #     bash .buildkite/scripts/ads_run_models.sh databricks
