steps:
## Ads Packages 1
  - label: ":snowflake: Run Tests - Ads Packages :bookmark: :one:"
    key: "run_dbt_snowflake_ads"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_SNOWFLAKE_DBT_ACCOUNT"
            - "CI_SNOWFLAKE_DATABASE_FT_UTILS"
            - "CI_SNOWFLAKE_DBT_PASS"
            - "CI_SNOWFLAKE_DBT_ROLE_FT_UTILS_TEST"
            - "CI_SNOWFLAKE_DBT_USER"
            - "CI_SNOWFLAKE_DBT_WAREHOUSE"
    commands: |
      bash .buildkite/scripts/ads_run_models.sh snowflake linkedin apple_search_ads snapchat_ads facebook_ads google_ads microsoft_ads

  - label: ":postgres: Run Tests - Ads Packages :bookmark: :one:"
    key: "run-dbt-postgres-ads"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_POSTGRES_DBT_DBNAME"
            - "CI_POSTGRES_DBT_HOST"
            - "CI_POSTGRES_DBT_PASS"
            - "CI_POSTGRES_DBT_USER"
    commands: |
      bash .buildkite/scripts/ads_run_models.sh postgres linkedin apple_search_ads snapchat_ads facebook_ads google_ads microsoft_ads

  - label: ":gcloud: Run Tests - Ads Packages :bookmark: :one:"
    key: "run_dbt_bigquery_ads"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "GCLOUD_SERVICE_KEY"
    commands: |
      bash .buildkite/scripts/ads_run_models.sh bigquery linkedin apple_search_ads snapchat_ads facebook_ads google_ads microsoft_ads

  - label: ":amazon-redshift: Run Tests - Ads Packages :bookmark: :one:"
    key: "run_dbt_redshift_ads"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_REDSHIFT_DBT_DBNAME"
            - "CI_REDSHIFT_DBT_HOST"
            - "CI_REDSHIFT_DBT_PASS"
            - "CI_REDSHIFT_DBT_USER"
    commands: |
      bash .buildkite/scripts/ads_run_models.sh redshift linkedin apple_search_ads snapchat_ads facebook_ads google_ads microsoft_ads

  - label: ":bricks: Run Tests - Ads Packages :bookmark: :one:"
    key: "run_dbt_databricks_ads"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_DATABRICKS_DBT_HOST"
            - "CI_DATABRICKS_DBT_HTTP_PATH"
            - "CI_DATABRICKS_DBT_TOKEN"
    commands: |
      bash .buildkite/scripts/ads_run_models.sh databricks linkedin apple_search_ads snapchat_ads facebook_ads google_ads microsoft_ads

## Ads Packages 2
  - label: ":snowflake: Run Tests - Ads Packages :bookmark: :two:"
    key: "run_dbt_snowflake_ads"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_SNOWFLAKE_DBT_ACCOUNT"
            - "CI_SNOWFLAKE_DATABASE_FT_UTILS"
            - "CI_SNOWFLAKE_DBT_PASS"
            - "CI_SNOWFLAKE_DBT_ROLE_FT_UTILS_TEST"
            - "CI_SNOWFLAKE_DBT_USER"
            - "CI_SNOWFLAKE_DBT_WAREHOUSE"
    commands: |
      bash .buildkite/scripts/ads_run_models.sh snowflake tiktok_ads twitter_ads amazon_ads reddit_ads pinterest

  - label: ":postgres: Run Tests - Ads Packages :bookmark: :two:"
    key: "run-dbt-postgres-ads"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_POSTGRES_DBT_DBNAME"
            - "CI_POSTGRES_DBT_HOST"
            - "CI_POSTGRES_DBT_PASS"
            - "CI_POSTGRES_DBT_USER"
    commands: |
      bash .buildkite/scripts/ads_run_models.sh postgres tiktok_ads twitter_ads amazon_ads reddit_ads pinterest

  - label: ":gcloud: Run Tests - Ads Packages :bookmark: :two:"
    key: "run_dbt_bigquery_ads"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "GCLOUD_SERVICE_KEY"
    commands: |
      bash .buildkite/scripts/ads_run_models.sh bigquery tiktok_ads twitter_ads amazon_ads reddit_ads pinterest

  - label: ":amazon-redshift: Run Tests - Ads Packages :bookmark: :two:"
    key: "run_dbt_redshift_ads"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_REDSHIFT_DBT_DBNAME"
            - "CI_REDSHIFT_DBT_HOST"
            - "CI_REDSHIFT_DBT_PASS"
            - "CI_REDSHIFT_DBT_USER"
    commands: |
      bash .buildkite/scripts/ads_run_models.sh redshift tiktok_ads twitter_ads amazon_ads reddit_ads pinterest

  - label: ":bricks: Run Tests - Ads Packages :bookmark: :two:"
    key: "run_dbt_databricks_ads"
    plugins:
      - docker#v3.13.0:
          image: "python:3.8"
          shell: [ "/bin/bash", "-e", "-c" ]
          environment:
            - "BASH_ENV=/tmp/.bashrc"
            - "CI_DATABRICKS_DBT_HOST"
            - "CI_DATABRICKS_DBT_HTTP_PATH"
            - "CI_DATABRICKS_DBT_TOKEN"
    commands: |
      bash .buildkite/scripts/ads_run_models.sh databricks tiktok_ads twitter_ads amazon_ads reddit_ads pinterest
