name: 'fivetran_utils_integration_tests'
version: '0.4.2'
config-version: 2
profile: 'integration_tests'

models:
  fivetran_utils_schema: 'fivetran_utils_integration_tests'
  twitter_ads:
    +tags: twitter_ads
  zendesk:
    +tags: zendesk
    intermediate:
      int_zendesk__ticket_schedules:
        +enabled: False
    utils:
      int_zendesk__calendar_spine:
        +enabled: False
    ticket_history:
      int_zendesk__field_history_pivot:
        +enabled: False

  hubspot:
    +tags: hubspot
  klaviyo:
    +tags: klaviyo
  jira: 
    intermediate:
      field_history:
        int_jira__issue_calendar_spine:
          +enabled: False
    +tags: jira

vars:
  zendesk_schedule: "{{ source('zendesk', 'schedule') }}"
  zendesk_ticket: "{{ source('zendesk', 'ticket') }}"
  zendesk_ticket_field_history: "{{ source('zendesk', 'ticket_field_history') }}"

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"