name: 'fivetran_utils_integration_tests'
version: '0.4.2'
config-version: 2
profile: 'integration_tests'

models:
  ad_reporting:
    +tags: ad_reporting
  zendesk:
    +tags: zendesk
  hubspot:
    +tags: hubspot
  netsuite:
    +tags: netsuite
  jira: 
    +tags: jira

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"