name: 'fivetran_utils_integration_tests'
version: '0.4.1'
config-version: 2
profile: 'integration_tests'

models:
  ad_reporting:
    +tags: ad_reporting
  zendesk:
    +tags: zendesk
  hubspot:
    +tags: hubspot
  netsuite:
    +tags: netsuite
  jira: 
    +tags: jira


dispatch:
  - macro_namespace: fivetran_utils
    search_order: ['fivetran_utils_test','fivetran_utils']