name: 'fivetran_utils_integration_tests'
version: '0.4.2'
config-version: 2
profile: 'integration_tests'

models:
  fivetran_utils_schema: 'fivetran_utils_integration_tests'
  ad_reporting:
    +tags: ad_reporting
  # zendesk:
  #   +tags: zendesk
  hubspot:
    +tags: hubspot
  netsuite:
    +tags: netsuite
  jira: 
    # intermediate:
    #   int_jira__project_metrics:
    #     +enabled: False 
    #   int_jira__user_metrics:
    #     +enabled: False
    #   field_history:
    #     int_jira__issue_calendar_spine:
    #       +enabled: False
    # jira__daily_issue_field_history:
    #   +enabled: False
    # jira__issue_enhanced:
    #   +enabled: False
    # jira__user_enhanced:
    #   +enabled: False
    # jira__project_enhanced:
    #   +enabled: False
    +tags: jira

vars:
  ## Ad Reporting
  ad_reporting__apple_search_ads_enabled: False
  ad_reporting__pinterest_ads_enabled: False
  ad_reporting__microsoft_ads_enabled: True
  ad_reporting__linkedin_ads_enabled: False
  ad_reporting__google_ads_enabled: True
  ad_reporting__twitter_ads_enabled: False
  ad_reporting__facebook_ads_enabled: True
  ad_reporting__snapchat_ads_enabled: False
  ad_reporting__tiktok_ads_enabled: False
  microsoft_ads_schema: "{{ env_var('MICROSOFT_ADS_SCHEMA') }}"
  facebook_ads_schema: "{{ env_var('FACEBOOK_ADS_SCHEMA') }}"
  google_ads_schema:  "{{ env_var('GOOGLE_ADS_SCHEMA') }}"

  netsuite_schema: "{{ env_var('NETSUITE_SCHEMA') }}"

  jira_schema: "{{ env_var('JIRA_SCHEMA') }}"

  # zendesk_database: "{{ env_var('BIGQUERY_DATABASE') }}"
  # zendesk_schema: "{{ env_var('ZENDESK_SCHEMA') }}"

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"