name: 'fivetran_utils_integration_tests'
version: '0.4.2'
config-version: 2
profile: 'integration_tests'

models:
  fivetran_utils_schema: 'fivetran_utils_integration_tests'
  twitter_ads:
    +tags: twitter_ads
  zendesk:
    +tags: zendesk
  hubspot:
    +tags: hubspot
  klaviyo:
    +tags: klaviyo
  jira: 
    intermediate:
      field_history:
        int_jira__issue_calendar_spine:
          +enabled: False
    +tags: jira

clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"